// <auto-generated />
namespace web.artimeagallery.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class arvixe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(arvixe));
        
        string IMigrationMetadata.Id
        {
            get { return "201508162131031_arvixe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
